#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
restore0Dir
runApplication blockMesh
runApplication -s 1 topoSet -dict system/topoSetDict1
runApplication -s 1 refineMesh -overwrite
runApplication mergeMeshes . ../floatingBody -overwrite
runApplication -s 2 topoSet -dict system/topoSetDict2
runApplication setFields
runApplication decomposePar



#------------------------------------------------------------------------------
